export const s = {
  root: { display:'flex', height:'100vh', overflow:'hidden', background:'#0e0e0e', color:'#e0e0e0', fontFamily:"'Inter','Segoe UI',system-ui,sans-serif" },
  sidebar: { width:230, background:'#141414', borderRight:'1px solid #2a2a2a', display:'flex', flexDirection:'column', gap:2, padding:'16px 10px', position:'sticky', top:0, height:'100vh', overflowY:'auto' },
  logo: { display:'flex', alignItems:'center', gap:10, padding:'8px 10px 18px', borderBottom:'1px solid #2a2a2a', marginBottom:6 },
  logoIcon: { fontSize:22 },
  logoText: { fontSize:17, fontWeight:800, color:'#e0e0e0', letterSpacing:'-0.5px' },
  xpCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:12, marginBottom:8 },
  xpRow: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:6 },
  lvlBadge: { background:'#22c55e12', color:'#22c55e', border:'1px solid #22c55e33', padding:'2px 10px', borderRadius:0, fontSize:11, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.05em' },
  xpLabel: { color:'#888888', fontSize:10, textTransform:'uppercase', letterSpacing:'0.05em' },
  xpBarBg: { height:4, background:'#0e0e0e', borderRadius:0, overflow:'hidden' },
  xpBarFill: { height:'100%', background:'#22c55e', borderRadius:0, transition:'width 0.4s' },
  xpSub: { color:'#555555', fontSize:9, marginTop:4 },
  navBtn: { display:'flex', alignItems:'center', gap:10, padding:'9px 12px', borderRadius:0, background:'transparent', border:'none', cursor:'pointer', color:'#888888', fontSize:13, fontWeight:500, width:'100%', textAlign:'left', transition:'all 0.15s' },
  navBtnActive: { background:'#1a1a1a', color:'#e0e0e0', borderLeft:'2px solid #22c55e' },
  streakCard: { marginTop:'auto', background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:14, textAlign:'center' },
  streakNum: { fontSize:22, fontWeight:800, color:'#22c55e' },
  streakLabel: { color:'#888888', fontSize:10, marginTop:2, textTransform:'uppercase', letterSpacing:'0.05em' },
  main: { flex:1, padding:'28px 36px', overflowY:'auto', maxWidth:920, height:'100vh', paddingBottom:60 },
  pageTitle: { fontSize:24, fontWeight:800, color:'#e0e0e0', margin:0, letterSpacing:'-0.3px' },
  pageSub: { color:'#888888', fontSize:12, marginTop:4, marginBottom:20 },
  pageHeader: { display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:8 },
  sectionTitle: { fontWeight:700, color:'#555555', margin:'24px 0 10px', textTransform:'uppercase', letterSpacing:'0.1em', fontSize:10 },
  statGrid: { display:'grid', gridTemplateColumns:'repeat(4,1fr)', gap:12, marginBottom:8 },
  statColor: { borderRadius:0, padding:'16px 14px', border:'1px solid #2a2a2a' },
  statValue: { fontSize:24, fontWeight:800, marginBottom:2 },
  statLabel: { fontSize:11, fontWeight:600, opacity:0.7, textTransform:'uppercase', letterSpacing:'0.05em' },
  statSub: { fontSize:10, opacity:0.5, marginTop:2 },
  habitList: { display:'flex', flexDirection:'column', gap:8 },
  habitRow: { display:'flex', alignItems:'center', gap:12, background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:'12px 14px', transition:'all 0.2s' },
  habitRowDone: { opacity:0.5 },
  habitIconBig: { fontSize:22 },
  habitInfo: { flex:1 },
  habitName: { color:'#e0e0e0', fontWeight:600, fontSize:13 },
  habitCat: { fontSize:11, marginTop:2, color:'#555555' },
  checkBtn: { width:30, height:30, borderRadius:0, border:'2px solid #2a2a2a', background:'transparent', cursor:'pointer', color:'transparent', fontSize:14, display:'flex', alignItems:'center', justifyContent:'center', transition:'all 0.15s' },
  checkBtnDone: { background:'#22c55e', border:'2px solid #22c55e', color:'#fff' },
  chartBox: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:'16px 10px 10px', marginBottom:8 },
  addBtn: { background:'#22c55e', border:'none', color:'#fff', padding:'9px 18px', borderRadius:0, cursor:'pointer', fontWeight:700, fontSize:12, textTransform:'uppercase', letterSpacing:'0.05em' },
  addCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:18, marginBottom:20 },
  formRow: { display:'flex', gap:8, flexWrap:'wrap', alignItems:'center' },
  input: { background:'#222222', border:'1px solid #2a2a2a', color:'#e0e0e0', padding:'9px 12px', borderRadius:0, fontSize:12, outline:'none', flex:1, minWidth:100 },
  select: { background:'#222222', border:'1px solid #2a2a2a', color:'#e0e0e0', padding:'9px 12px', borderRadius:0, fontSize:12, outline:'none' },
  gridCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, overflow:'hidden' },
  gridHeader: { display:'flex', alignItems:'center', padding:'10px 14px', borderBottom:'1px solid #2a2a2a', background:'#141414' },
  gridDay: { width:48, textAlign:'center', color:'#888888', fontSize:11, fontWeight:600, textTransform:'uppercase' },
  gridRow: { display:'flex', alignItems:'center', padding:'8px 14px', borderBottom:'1px solid #2a2a2a' },
  gridHabitName: { width:170, display:'flex', alignItems:'center', gap:8 },
  gridCell: { width:48, display:'flex', alignItems:'center', justifyContent:'center' },
  gridCheck: { width:24, height:24, borderRadius:0, border:'1px solid #2a2a2a', background:'transparent', cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', transition:'all 0.15s' },
  deleteBtn: { background:'transparent', border:'none', color:'#555555', cursor:'pointer', fontSize:11, padding:'2px 6px', marginLeft:6 },
  calGrid: { display:'grid', gridTemplateColumns:'repeat(7,1fr)', gap:3, background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:10 },
  calDayName: { textAlign:'center', color:'#555555', fontSize:10, fontWeight:700, padding:'3px 0 6px', textTransform:'uppercase' },
  calDay: { aspectRatio:'1', borderRadius:0, background:'#222222', border:'1px solid #2a2a2a', color:'#888888', fontSize:11, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', transition:'all 0.15s' },
  navArrow: { background:'#1a1a1a', border:'1px solid #2a2a2a', color:'#888888', width:34, height:34, borderRadius:0, cursor:'pointer', fontSize:16, display:'flex', alignItems:'center', justifyContent:'center' },
  badgeGrid: { display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:12, marginBottom:20 },
  badgeCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:'18px 14px', textAlign:'center', transition:'all 0.2s' },
  badgeCardEarned: { border:'1px solid #22c55e33', background:'#22c55e08' },
  excelBtn: { display:'flex', alignItems:'center', gap:8, padding:'9px 12px', borderRadius:0, background:'transparent', border:'1px solid #2a2a2a', cursor:'pointer', color:'#888888', fontSize:12, fontWeight:500, width:'100%', textAlign:'left', transition:'all 0.15s', marginBottom:4 },

  // Medicine styles
  medCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderLeft:'3px solid #22c55e', borderRadius:0, padding:'14px 16px', marginBottom:8 },
  medTime: { color:'#555555', fontSize:10, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.1em', margin:'20px 0 8px', padding:'0 2px' },
  medPill: { display:'flex', alignItems:'center', gap:12, padding:'10px 14px', background:'#141414', border:'1px solid #2a2a2a', borderRadius:0, marginBottom:4 },
  medTakeBtn: { background:'#22c55e', border:'none', color:'#fff', padding:'5px 14px', borderRadius:0, cursor:'pointer', fontWeight:700, fontSize:11, textTransform:'uppercase', letterSpacing:'0.05em' },
  medSkipBtn: { background:'transparent', border:'1px solid #3a2020', color:'#ef4444', padding:'5px 14px', borderRadius:0, cursor:'pointer', fontWeight:600, fontSize:11, textTransform:'uppercase', letterSpacing:'0.05em' },

  // Timeline / daily routine styles
  timelineWrap: { display:'flex', flexDirection:'column', gap:0, position:'relative', paddingLeft:20 },
  timelineBlock: { borderLeft:'2px solid #2a2a2a', padding:'12px 16px', marginLeft:6, position:'relative' },
  timelineTime: { color:'#555555', fontSize:10, fontWeight:700, textTransform:'uppercase', letterSpacing:'0.1em', position:'absolute', left:-28, top:12, width:22, textAlign:'right' },
  timelineNow: { position:'absolute', left:0, right:0, height:2, background:'#22c55e', zIndex:2 },

  // Widget / dashboard styles
  widgetRow: { display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:12, marginBottom:12 },
  widgetCard: { background:'#1a1a1a', border:'1px solid #2a2a2a', borderRadius:0, padding:'16px 14px' },
  waterDot: { width:20, height:20, borderRadius:0, border:'1px solid #2a2a2a', background:'#222222', display:'inline-flex', alignItems:'center', justifyContent:'center', cursor:'pointer', marginRight:4, transition:'all 0.15s', fontSize:12 },
  moodBtn: { width:36, height:36, borderRadius:0, border:'1px solid #2a2a2a', background:'#222222', cursor:'pointer', fontSize:18, display:'flex', alignItems:'center', justifyContent:'center', transition:'all 0.15s' },
  noteInput: { background:'#222222', border:'1px solid #2a2a2a', color:'#e0e0e0', padding:'10px 12px', borderRadius:0, fontSize:12, outline:'none', width:'100%', minHeight:60, resize:'vertical', fontFamily:'inherit' },
}
